- hosts: all
  remote_user: vagrant
  become: yes
  tasks:
    - name: Ajustando o Timezone do Servidor 
      timezone:
        name: America/Sao_Paulo
 

#CONTROLLER
- hosts: controllers
  remote_user: vagrant
  become: yes
  tasks:
    - name: Criando o Arquivo Info
      lineinfile:
        path: /tmp/info
        line: SERVIDOR ANSIBLE CONTROLLER
        create: yes

#DATABASE
- hosts: database
  remote_user: vagrant
  become: yes
  tasks:
    - name: Criando o Arquivo Info
      lineinfile:
        path: /tmp/info
        line: SERVIDOR DE BANCO DE DADOS MYSQL
        create: yes
        
    - name: Instalação do MYSQL servidor banco de dados
      apt: 
        state: present 
        pkg:
          - mysql-server
              

#WEBSERVERS
- hosts: webservers
  remote_user: vagrant
  become: yes
  tasks:
    - name: Criando o Arquivo Info
      lineinfile:
        path: /tmp/info
        line: SERVIDOR DO BLOG WORDPRESS
        create: yes
        
    - name: Instalação do Apache e PHP
      apt: 
        state: present 
        update_cache: yes
        pkg:
          - apache2
          - php-curl
          - php-gd
          - php-mbstring
          - php-xml
          - php-xmlrpc
          - php-soap
          - php-intl
          - php-zip
          - php 
          - libapache2-mod-php 
          - php-mysql
          - php-cli
 
 
 









